//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRDS.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the List of Accounts and Their Assigned Roles.
        /// </summary>
        public static string AccountsAndAssignedRolesOverview {
            get {
                return ResourceManager.GetString("AccountsAndAssignedRolesOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Overview.
        /// </summary>
        public static string ActionsOverview {
            get {
                return ResourceManager.GetString("ActionsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Screen.
        /// </summary>
        public static string ActivateScreen {
            get {
                return ResourceManager.GetString("ActivateScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the Active System Modules and Software Sections.
        /// </summary>
        public static string ActiveSystemModulesAndSections {
            get {
                return ResourceManager.GetString("ActiveSystemModulesAndSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New City.
        /// </summary>
        public static string AddNewCity {
            get {
                return ResourceManager.GetString("AddNewCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Country.
        /// </summary>
        public static string AddNewCountry {
            get {
                return ResourceManager.GetString("AddNewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Gender.
        /// </summary>
        public static string AddNewGende {
            get {
                return ResourceManager.GetString("AddNewGende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Governorate.
        /// </summary>
        public static string AddNewGovernorate {
            get {
                return ResourceManager.GetString("AddNewGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Marital Status.
        /// </summary>
        public static string AddNewMaritalStatus {
            get {
                return ResourceManager.GetString("AddNewMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Military Status.
        /// </summary>
        public static string AddNewMilitaryStatus {
            get {
                return ResourceManager.GetString("AddNewMilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Nationality.
        /// </summary>
        public static string AddNewNationality {
            get {
                return ResourceManager.GetString("AddNewNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Permission.
        /// </summary>
        public static string AddNewPermission {
            get {
                return ResourceManager.GetString("AddNewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Religion.
        /// </summary>
        public static string AddNewReligion {
            get {
                return ResourceManager.GetString("AddNewReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Role.
        /// </summary>
        public static string AddNewRole {
            get {
                return ResourceManager.GetString("AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Screen.
        /// </summary>
        public static string AddNewScreen {
            get {
                return ResourceManager.GetString("AddNewScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Roles.
        /// </summary>
        public static string AssignRoles {
            get {
                return ResourceManager.GetString("AssignRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Data.
        /// </summary>
        public static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities Management.
        /// </summary>
        public static string CitiesManagement {
            get {
                return ResourceManager.GetString("CitiesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Code.
        /// </summary>
        public static string CityCode {
            get {
                return ResourceManager.GetString("CityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (2).
        /// </summary>
        public static string Code2 {
            get {
                return ResourceManager.GetString("Code2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code (3).
        /// </summary>
        public static string Code3 {
            get {
                return ResourceManager.GetString("Code3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Code.
        /// </summary>
        public static string CodeGender {
            get {
                return ResourceManager.GetString("CodeGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status Code.
        /// </summary>
        public static string CodeMaritalStatus {
            get {
                return ResourceManager.GetString("CodeMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Status Code.
        /// </summary>
        public static string CodeMilitaryStatus {
            get {
                return ResourceManager.GetString("CodeMilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Code.
        /// </summary>
        public static string CodeNationality {
            get {
                return ResourceManager.GetString("CodeNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion Code.
        /// </summary>
        public static string CodeReligion {
            get {
                return ResourceManager.GetString("CodeReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Branches.
        /// </summary>
        public static string CompanyBranches {
            get {
                return ResourceManager.GetString("CompanyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuratin Data.
        /// </summary>
        public static string ConfiguratinData {
            get {
                return ResourceManager.GetString("ConfiguratinData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Management.
        /// </summary>
        public static string CountryManagement {
            get {
                return ResourceManager.GetString("CountryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit City.
        /// </summary>
        public static string EditCity {
            get {
                return ResourceManager.GetString("EditCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country.
        /// </summary>
        public static string EditCountry {
            get {
                return ResourceManager.GetString("EditCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Gender.
        /// </summary>
        public static string EditGende {
            get {
                return ResourceManager.GetString("EditGende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Governorate.
        /// </summary>
        public static string EditGovernorate {
            get {
                return ResourceManager.GetString("EditGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Marital Status.
        /// </summary>
        public static string EditMaritalStatus {
            get {
                return ResourceManager.GetString("EditMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Military Status.
        /// </summary>
        public static string EditMilitaryStatus {
            get {
                return ResourceManager.GetString("EditMilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Nationality.
        /// </summary>
        public static string EditNationality {
            get {
                return ResourceManager.GetString("EditNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string EditPermission {
            get {
                return ResourceManager.GetString("EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Religion.
        /// </summary>
        public static string EditReligion {
            get {
                return ResourceManager.GetString("EditReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Screen.
        /// </summary>
        public static string EditScreen {
            get {
                return ResourceManager.GetString("EditScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender Management.
        /// </summary>
        public static string GendersManagement {
            get {
                return ResourceManager.GetString("GendersManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate Code.
        /// </summary>
        public static string GovernorateCode {
            get {
                return ResourceManager.GetString("GovernorateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorates Management.
        /// </summary>
        public static string GovernoratesManagement {
            get {
                return ResourceManager.GetString("GovernoratesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Module.
        /// </summary>
        public static string MainModule {
            get {
                return ResourceManager.GetString("MainModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Actions.
        /// </summary>
        public static string ManageActions {
            get {
                return ResourceManager.GetString("ManageActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Management.
        /// </summary>
        public static string ManageCompanies {
            get {
                return ResourceManager.GetString("ManageCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Permissions.
        /// </summary>
        public static string ManagePermissions {
            get {
                return ResourceManager.GetString("ManagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status Management.
        /// </summary>
        public static string MaritalStatusManagement {
            get {
                return ResourceManager.GetString("MaritalStatusManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Status Management.
        /// </summary>
        public static string MilitaryStatusManagement {
            get {
                return ResourceManager.GetString("MilitaryStatusManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Code.
        /// </summary>
        public static string ModuleCode {
            get {
                return ResourceManager.GetString("ModuleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules Overview.
        /// </summary>
        public static string ModulesOverview {
            get {
                return ResourceManager.GetString("ModulesOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality Management.
        /// </summary>
        public static string NationalitiesManagement {
            get {
                return ResourceManager.GetString("NationalitiesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Code.
        /// </summary>
        public static string OperationCode {
            get {
                return ResourceManager.GetString("OperationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Module.
        /// </summary>
        public static string ParentModule {
            get {
                return ResourceManager.GetString("ParentModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Code.
        /// </summary>
        public static string PermissionCode {
            get {
                return ResourceManager.GetString("PermissionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Management.
        /// </summary>
        public static string PermissionsManagement {
            get {
                return ResourceManager.GetString("PermissionsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Overview.
        /// </summary>
        public static string PermissionsOverview {
            get {
                return ResourceManager.GetString("PermissionsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the List of Permissions and Their Relationships with Screens and Actions.
        /// </summary>
        public static string PermissionsScreensActionsOverview {
            get {
                return ResourceManager.GetString("PermissionsScreensActionsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string PleaseSelectCountry {
            get {
                return ResourceManager.GetString("PleaseSelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a governorate.
        /// </summary>
        public static string PleaseSelectGovernorate {
            get {
                return ResourceManager.GetString("PleaseSelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion Management.
        /// </summary>
        public static string ReligionManagement {
            get {
                return ResourceManager.GetString("ReligionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Code.
        /// </summary>
        public static string RoleCode {
            get {
                return ResourceManager.GetString("RoleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Code.
        /// </summary>
        public static string ScreenCode {
            get {
                return ResourceManager.GetString("ScreenCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screens Overview.
        /// </summary>
        public static string ScreensOverview {
            get {
                return ResourceManager.GetString("ScreensOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Data.
        /// </summary>
        public static string SecurityData {
            get {
                return ResourceManager.GetString("SecurityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        public static string SelectAction {
            get {
                return ResourceManager.GetString("SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...Select Country....
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Governorate.
        /// </summary>
        public static string SelectGovernorate {
            get {
                return ResourceManager.GetString("SelectGovernorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Module.
        /// </summary>
        public static string SelectModule {
            get {
                return ResourceManager.GetString("SelectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Screen.
        /// </summary>
        public static string SelectScreen {
            get {
                return ResourceManager.GetString("SelectScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Status.
        /// </summary>
        public static string ToggleStatus {
            get {
                return ResourceManager.GetString("ToggleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Overview.
        /// </summary>
        public static string UsersOverview {
            get {
                return ResourceManager.GetString("UsersOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit City Data in the System.
        /// </summary>
        public static string ViewAddEditCities {
            get {
                return ResourceManager.GetString("ViewAddEditCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Country Data in the System.
        /// </summary>
        public static string ViewAddEditCountries {
            get {
                return ResourceManager.GetString("ViewAddEditCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Gender Data in the System.
        /// </summary>
        public static string ViewAddEditGender {
            get {
                return ResourceManager.GetString("ViewAddEditGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Governorate Data in the System.
        /// </summary>
        public static string ViewAddEditGovernorates {
            get {
                return ResourceManager.GetString("ViewAddEditGovernorates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Marital Status Data in the System.
        /// </summary>
        public static string ViewAddEditMaritalStatus {
            get {
                return ResourceManager.GetString("ViewAddEditMaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Military Status Data in the System.
        /// </summary>
        public static string ViewAddEditMilitaryStatus {
            get {
                return ResourceManager.GetString("ViewAddEditMilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Nationality Data in the System.
        /// </summary>
        public static string ViewAddEditNationality {
            get {
                return ResourceManager.GetString("ViewAddEditNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, and Edit Religion Data in the System.
        /// </summary>
        public static string ViewAddEditReligion {
            get {
                return ResourceManager.GetString("ViewAddEditReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Select Job Roles and Assign Their Permissions.
        /// </summary>
        public static string ViewAndAssignRolePermissions {
            get {
                return ResourceManager.GetString("ViewAndAssignRolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Manage System Screens for Each Module.
        /// </summary>
        public static string ViewAndManageModuleScreens {
            get {
                return ResourceManager.GetString("ViewAndManageModuleScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Select the Basic Actions and Operations Available in the System.
        /// </summary>
        public static string ViewAndSelectSystemActionsAndOperations {
            get {
                return ResourceManager.GetString("ViewAndSelectSystemActionsAndOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
